# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4848c7b8b1d9ec78f7b071dba5160966e4c45870e8fcb9c126248456ef00a9b84a3b32c3e2b555eab6c668c5b0fd79958c96108f65f2ecd1f82b4d1f97529a9

test:
  secret_key_base: cb84b4664627dcafae79d7b5da9aa139bb04e8ce710c394542132621161b03bd72ed2785c16ac93425a3cc16c1a13a7fa7c512fff0b4614a7c959668163e5f74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
