Contact.create(name:"Fran", address:"c/ Cochabamba 7" )
Contact.create(name:"Jose Luis", address:"c/ María de Molina 40" )
Contact.create(name:"Guillermo", address:"c/ Juan bravo 1" )
Contact.create(name:"Pablo", address:"c/ Predro Texeira 5" )
Contact.create(name:"Elena", address:"c/ Hermosilla 79" )

Number.create(phone_number:628053456, contact_id: 1)
Number.create(phone_number:628405456, contact_id: 2)
Number.create(phone_number:628403866, contact_id: 3)
Number.create(phone_number:628407543, contact_id: 4)
Number.create(phone_number:628434572, contact_id: 5)
Number.create(phone_number:628234891, contact_id: 1)
Number.create(phone_number:628937424, contact_id: 2)
Number.create(phone_number:628957321, contact_id: 3)
Number.create(phone_number:628412344, contact_id: 4)
Number.create(phone_number:628742462, contact_id: 5)

Address.create(email_address: "example@gmail.com", contact_id: 1)
Address.create(email_address: "example@gmail.com", contact_id: 2)
Address.create(email_address: "example@gmail.com", contact_id: 3)
Address.create(email_address: "example@gmail.com", contact_id: 4)
Address.create(email_address: "example@gmail.com", contact_id: 5)
Address.create(email_address: "example@gmail.com", contact_id: 1)
Address.create(email_address: "example@gmail.com", contact_id: 2)
Address.create(email_address: "example@gmail.com", contact_id: 3)
Address.create(email_address: "example@gmail.com", contact_id: 4)
Address.create(email_address: "example@gmail.com", contact_id: 5)